---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker-py
before_script:
  - cd ../
  - mv ansible-chubbs chubbs
  - cd chubbs
script:
  - travis_wait molecule test