---
- name: Add spatial-server system group
  group:
    name: "{{ chubbs_system_group }}"
    state: present

- name: Add spatial-server system user
  user:
    name: "{{ chubbs_system_user }}"
    shell: /bin/bash
    group: "{{ chubbs_system_group }}"
    groups: "{{ chubbs_system_groups }}"
    append: yes
    createhome: yes
    home: "{{ chubbs_system_user_home }}"


- name: Install Node Version Manager
  include_role:
    name: onaio.nvm
  vars:
    nvm_user: "{{ chubbs_system_user }}"
    nvm_group: "{{ chubbs_system_group }}"
    nvm_node_version: "{{ chubbs_nvm_node_version }}"
    nvm_install_path: "{{ chubbs_nvm_install_path }}"
    nvm_node_dir: "{{ chubbs_nvm_node_dir }}"
    nvm_npm_path: "{{ chubbs_nvm_npm_path }}"
    nvm_version: "{{ chubbs_nvm_version }}"

- name: Install dependencies
  apt:
    update_cache: yes
    name: "{{ item }}"
  with_items: "{{ chubbs_apt_dependencies }}"
  tags:
    - mapnik

# install mapnik
- name: Clone the mapnik repo
  git:
    repo: "{{ chubbs_mapnik_git_url }}"
    version: "{{ chubbs_mapnik_version }}"
    depth: 10
    dest: "{{ chubbs_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Run the bootstrap file # noqa 301 305
  shell: ./bootstrap.sh
  args:
    chdir: "{{ chubbs_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Run the configure script # noqa 301 305
  shell: ./configure  CUSTOM_CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" CXX="clang++-3.8" CC="clang-3.8"
  args:
    chdir: "{{ chubbs_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Make Install
  make:
    target: install
    chdir: "{{ chubbs_mapnik_install_dir }}"
  tags:
    - mapnik

- name: Install Node.js Packages
  become: true
  become_user: "{{ chubbs_system_user }}"
  npm:
    global: yes
    name: pm2
    executable: "{{ chubbs_nvm_npm_path }}"
  environment:
    PATH: "{{ chubbs_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"

- name: Download PGRestAPI
  become: true
  become_user: "{{ chubbs_system_user }}"
  git:
    repo: "{{ chubbs_git_url }}"
    dest: "{{ chubbs_checkout_path }}"
    version: "{{ chubbs_version }}"
    depth: 1

- name: Install PGRestAPI npm packages
  become: true
  become_user: "{{ chubbs_system_user }}"
  unarchive:
    src: "{{ chubbs_npm_packages_archive_url }}"
    dest: "{{ chubbs_checkout_path }}"
    remote_src: yes

- name: Copy chubbs server settings.js to settings directory
  template:
    src: chubbs_checkout_path/settings/settings.js.j2
    dest: "{{ chubbs_checkout_path }}/settings/settings.js"
    mode: 0644

- name: Make the new codebase current
  become: true
  become_user: "{{ chubbs_system_user }}"
  file:
    force: yes
    state: link
    dest: "{{ chubbs_codebase_path }}"
    src: "{{ chubbs_checkout_path }}"