---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: chubbs-ubuntu
    image: solita/ubuntu-systemd:16.04
    privileged: true
    command: /sbin/init
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
